task: embodied-scene
dataset_path: /your/path/to/embodied-eval-main/embodied_eval/data/EmbodiedScene/embodied_scene_data.json
dataset_kwargs:
  image_dir: /your/path/to/embodied-eval-main/embodied_eval/data/EmbodiedScene
load_from_disk: true
eval_split: null
doc_to_visual: !function process.embodied_scene_doc_to_visual
doc_to_text: !function process.embodied_scene_doc_to_text
doc_to_target: !function process.embodied_scene_doc_to_target
output_type: generate_until
generation_kwargs:
  max_new_tokens: 256
  temperature: 0
  do_sample: false
  top_p: 1.0
  num_beams: 1
# metrics
process_results: !function process.embodied_scene_process_results
metric_kwargs:
  metric: embodied_scene_score
  aggregation: !function process.embodied_scene_aggregate_results
  higher_is_better: true
