task: cosmos-holoassist
dataset_path: /your/path/to/embodied-eval-main/embodied_eval/data/cosmos/holoassist/holoassist_benchmark_qa_pairs.json
dataset_kwargs:
  video_dir: /your/path/to/embodied-eval-main/embodied_eval/data/cosmos/holoassist/
  sub_task: holoassist
  pre_prompt: ""
  post_prompt: "\nAnswer with the option's letter from the given choices directly."
load_from_disk: true
eval_split: null
dataset_name: holoassist
doc_to_visual: !function process.cosmos_doc_to_visual
doc_to_text: !function process.cosmos_doc_to_text
doc_to_target: !function process.cosmos_doc_to_target
output_type: generate_until
generation_kwargs:
  # MCQ tasks do not need very long generations; large values can easily OOM on GPU.
  max_new_tokens: 1024
  temperature: 0
  do_sample: false
  top_p: 1.0
  num_beams: 1
# metrics
process_results: !function process.cosmos_process_results
metric_kwargs:
  metric: accuracy
  aggregation: !function process.cosmos_aggregate_results
  higher_is_better: true





