task: vabench_mask
dataset_path: IffYuan/VABench-P
dataset_kwargs:
  pre_prompt: ""
  post_prompt: "Your answer should be wrapped in <Answer><point>[[x1,y1],[x2,y2],[x3,y3],[x4,y4],[x5,y5],[x6,y6],[x7,y7],[x8,y8]]</point></Answer>, where each coordinate is in 0-1000 (normalized)."
  metric_mode: mask
  coord_mode: normalized
  points_mode: fixed
  expected_points: 8
load_from_disk: true
eval_split: test
doc_to_visual: !function process.vabench_doc_to_visual
doc_to_text: !function process.vabench_doc_to_text
doc_to_target: "id"
output_type: generate_until
generation_kwargs:
  max_new_tokens: 2048
  temperature: 0
  do_sample: false
  top_p: 1.0
  num_beams: 1
process_results: !function process.vabench_process_results
metric_kwargs:
  metric: accuracy
  aggregation: !function process.vabench_aggregate_results
  higher_is_better: true
